Setup MIN_TIMESTAMP updater
accrescent/accrescent pull request #88
Opened 2022-09-06 09:30 UTC by elusive-m

Uses the [create-pull-request GitHub action by Peter Evans](https://github.com/peter-evans/create-pull-request) to create pull requests. As per the discussion in #51, the workflow runs every month but this can be changed.

Closes #51

2022-09-06 18:14 UTC, lberrymage requested changes
First of all, thank you! Just a few minor suggestions.

2022-09-06 18:14 UTC, lberrymage commented on .github/workflows/update-timestamp.yaml
> +        run: sed -i -E "s/^$CONSTANT = [[:digit:]]*$/$CONSTANT = $(date +'%s')/" $FILE
This will update `MIN_TIMESTAMP` to the Unix timestamp of the job runner. If the `timestamp` field of the [signed repository metadata](https://store.accrescent.app/repodata.0.json) is less than that, the client will be unable to fetch new metadata unless `timestamp` is reduced (which shouldn't be done if at all possible to preserve the value of downgrade protection).

Could you modify this to update the timestamp to the latest published value instead? It can be fetched via
`curl -s https://store.accrescent.app/repodata.0.json | jq '.timestamp'`.

2022-09-06 18:14 UTC, lberrymage commented on .github/workflows/update-timestamp.yaml
> +        uses: peter-evans/create-pull-request@v4.1.1
nit: Specifying only the major version is fine and more consistent with existing Actions.

2022-09-06 18:14 UTC, lberrymage commented on .github/workflows/update-timestamp.yaml
> +name: Update MIN_TIMESTAMP
nit: To be consistent with previous commits, could you change this to "Bump" instead of "Update?"

2022-09-06 18:14 UTC, lberrymage commented on .github/workflows/update-timestamp.yaml
> +          message: Update MIN_TIMESTAMP
Same as above: "Bump" instead of "Update" would be preferred.

2022-09-07 06:59 UTC, elusive-m commented on .github/workflows/update-timestamp.yaml
> +        uses: peter-evans/create-pull-request@v4.1.1
Done.

2022-09-07 06:59 UTC, elusive-m commented on .github/workflows/update-timestamp.yaml
> +name: Update MIN_TIMESTAMP
Done.

2022-09-07 07:00 UTC, elusive-m commented on .github/workflows/update-timestamp.yaml
> +          message: Update MIN_TIMESTAMP
Done. I've also renamed the file to `bump-timestamp.yaml`.

2022-09-07 07:02 UTC, elusive-m commented on .github/workflows/update-timestamp.yaml
> +        run: sed -i -E "s/^$CONSTANT = [[:digit:]]*$/$CONSTANT = $(date +'%s')/" $FILE
Done.

2022-09-07 15:16 UTC, lberrymage approved these changes
Looks good to me! Thanks for the PR.

2022-09-07 15:21 UTC, merged